name: snowflake-devops-demo

# Controls when the action will run. 
on:
  push:
    branches:
      - main
    paths:
      - 'migrations/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-snowflake-changes-job:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Create connections.toml
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_ROLE: ${{ secrets.SF_ROLE }}
          SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
          SF_DATABASE: ${{ secrets.SF_DATABASE }}
        run: |
          cat << EOF > connections.toml
          [snowflake]
          account = "${SF_ACCOUNT}"
          username = "${SF_USERNAME}"
          password =  "${SNOWFLAKE_PASSWORD}"
          role = "${SF_ROLE}"
          warehouse = "${SF_WAREHOUSE}"
          database =  "${SF_DATABASE}"
          EOF
          echo "connections.toml chmod step"
          chmod 0600 connections.toml

      - name: Debug workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          echo "Current directory: $(pwd)"
          echo "List of files in the current directory:"
          ls -la
          echo "List of files in the GITHUB_WORKSPACE:"
          ls -la $GITHUB_WORKSPACE
